{% set name = "jazal" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jazal-{{ version }}.tar.gz
  sha256: 6ff63cce5fc6aedddaa509d1a3ea32ab4aff5245c6d33877b1b593cbeb210b42

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - jazal
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GRV96/jazal
  summary: "Jazal performs certain verifications on file paths before a function or a script uses them."
  description: "See the README in the GitHub repository (home)."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GRV96
